lowercaseOutputName: true
rules:
- pattern: "org.geoserver<type=Global, name=geoServer><>(.*)"
  name: "geoserver_$1"
- pattern: "org.geoserver<type=OwsDispatcher, name=ows><>(.*)"
  name: "geoserver_ows_$1"