services:
  moon-db:
    image: postgres:13
    container_name: moon-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=moon-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    volumes:
      - ./repository/migrations:/docker-entrypoint-initdb.d
      - management_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d client" ]
      interval: 5s
      timeout: 5s
      retries: 5
